#!/bin/bash

# same configuration as applied in ./entrypoint
set -o errexit
set -o pipefail
set -o nounset

# Make sure to apply any migrations available.
echo "[DJANGO] Running migrations..."
python /app/manage.py migrate

echo "[DJANGO] Importing new templates..."
python manage.py load_finding_templates

# TODO: maybe run gunicorn
echo "[DJANGO] Starting server"
gunicorn sastf.SASTF.wsgi:application --bind 0.0.0.0:$DJANGO_PORT --workers 4 --threads 4
