# Generated by Django 4.2.14 on 2024-11-15 09:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sastf.SASTF.utils.enum


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Regular', 'Regular'), ('External', 'External')], default=sastf.SASTF.utils.enum.Role['REGULAR'], max_length=256)),
                ('description', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('permission_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('protection_level', models.TextField(blank=True)),
                ('dangerous', models.BooleanField(default=False)),
                ('group', models.CharField(blank=True, max_length=256)),
                ('short_description', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('risk', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('bundle_id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('tags', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info'), ('Secure', 'Secure'), ('None', 'None')], default=sastf.SASTF.utils.enum.Severity['NONE'], max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.CharField(blank=True, max_length=12)),
                ('sha1', models.CharField(blank=True, max_length=255)),
                ('sha256', models.CharField(blank=True, max_length=255)),
                ('issuer', models.TextField(blank=True)),
                ('subject', models.TextField(blank=True)),
                ('hash_algorithm', models.TextField(blank=True)),
                ('signature_algorithm', models.TextField(blank=True)),
                ('serial_number', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CipherSuite',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('cipher_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('recommended', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('cid', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2048)),
                ('is_exported', models.BooleanField(default=False)),
                ('is_protected', models.BooleanField(default=True)),
                ('is_launcher', models.BooleanField(default=False)),
                ('is_main', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, choices=[('Activity', 'Activity'), ('Service', 'Service'), ('Receiver', 'Receiver'), ('Provider', 'Provider'), ('Application', 'Application')], max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataCollectionGroup',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('dc_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=256)),
                ('protection_level', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default=sastf.SASTF.utils.enum.DataProtectionLevel['PUBLIC'], max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('dependency_uuid', models.CharField(max_length=72, primary_key=True, serialize=False)),
                ('relation', models.CharField(choices=[('Transitive', 'Transitive'), ('Direct', 'Direct')], default=sastf.SASTF.utils.enum.Relation['DIRECT'], max_length=256)),
                ('outdated', models.CharField(blank=True, max_length=512)),
                ('version', models.CharField(blank=True, max_length=512)),
                ('license', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('cvss', models.FloatField(default=0)),
                ('icon', models.CharField(blank=True, max_length=1024)),
                ('tracker_count', models.IntegerField(default=0)),
                ('app_name', models.CharField(blank=True, max_length=512)),
                ('app_id', models.CharField(blank=True, max_length=512)),
                ('app_version', models.CharField(blank=True, max_length=512)),
                ('target_sdk', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeveloperInfo',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('developer_id', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=512)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('env_id', models.UUIDField(primary_key=True, serialize=False)),
                ('allow_registration', models.BooleanField(default=True)),
                ('allow_teams', models.BooleanField(default=True)),
                ('max_projects', models.IntegerField(default=100000)),
                ('max_teams', models.IntegerField(default=10000)),
                ('max_bundles', models.IntegerField(default=10000)),
                ('first_start', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('md5', models.CharField(default='', max_length=32, primary_key=True, serialize=False)),
                ('sha256', models.CharField(default='', max_length=64)),
                ('sha1', models.CharField(default='', max_length=40)),
                ('file_name', models.CharField(default='', max_length=256)),
                ('file_size', models.CharField(default='', max_length=50)),
                ('file_path', models.CharField(blank=True, max_length=2048)),
                ('internal_name', models.CharField(default='', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('finding_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info'), ('Secure', 'Secure'), ('None', 'None')], default=sastf.SASTF.utils.enum.Severity['NONE'], max_length=256)),
                ('discovery_date', models.DateField(auto_now_add=True, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('custom_text', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FindingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('template_id', models.CharField(blank=True, max_length=128, unique=True)),
                ('internal_id', models.CharField(blank=True, max_length=256, unique=True)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField()),
                ('is_html', models.BooleanField(default=False)),
                ('is_contextual', models.BooleanField(default=False)),
                ('default_severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info'), ('Secure', 'Secure'), ('None', 'None')], default=sastf.SASTF.utils.enum.Severity['NONE'], max_length=256)),
                ('risk', models.TextField()),
                ('mitigation', models.TextField()),
                ('article', models.CharField(max_length=256)),
                ('meta_cvss', models.CharField(blank=True, max_length=256)),
                ('meta_cwe', models.CharField(blank=True, max_length=32)),
                ('meta_masvs', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('host_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('classification', models.CharField(choices=[('Invalid', 'Invalid'), ('Tracker', 'Tracker'), ('Malware', 'Malware'), ('Ok', 'Ok'), ('Not Set', 'Not Set')], default=sastf.SASTF.utils.enum.HostType['NOT_SET'], max_length=256)),
                ('url', models.CharField(blank=True, max_length=2048, null=True)),
                ('ip', models.CharField(max_length=32, null=True)),
                ('port', models.IntegerField(default=0)),
                ('protocol', models.CharField(max_length=256, null=True)),
                ('country', models.CharField(max_length=256, null=True)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostTemplate',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('template_id', models.UUIDField(primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=256)),
                ('ip_address', models.CharField(max_length=32, null=True)),
                ('owner', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntentFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=1024)),
                ('action', models.CharField(blank=True, max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('package_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=512)),
                ('artifact_id', models.CharField(blank=True, max_length=512)),
                ('group_id', models.CharField(blank=True, max_length=512)),
                ('package_type', models.CharField(choices=[('Github', 'Github'), ('Dart', 'Dart'), ('Cordova', 'Cordova'), ('Flutter', 'Flutter'), ('Native', 'Native'), ('Maven', 'Maven'), ('None', 'None')], default=sastf.SASTF.utils.enum.PackageType['NONE'], max_length=256)),
                ('platform', models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS'), ('Undefined', 'Undefined')], default=sastf.SASTF.utils.enum.Platform['UNKNOWN'], max_length=256)),
                ('is_tracker', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('project_uuid', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, unique=True)),
                ('tags', models.CharField(blank=True, max_length=4096)),
                ('visibility', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Internal', 'Internal')], default=sastf.SASTF.utils.enum.Visibility['PRIVATE'], max_length=256)),
                ('risk_level', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info'), ('Secure', 'Secure'), ('None', 'None')], default=sastf.SASTF.utils.enum.Severity['INFO'], max_length=256)),
                ('inspection_type', models.CharField(choices=[('Simple', 'Simple'), ('Advanced', 'Advanced')], default=sastf.SASTF.utils.enum.InspectionType['SIMPLE'], max_length=256)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('scan_uuid', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('origin', models.CharField(blank=True, max_length=32)),
                ('source', models.CharField(blank=True, max_length=256)),
                ('scan_type', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(null=True)),
                ('status', models.CharField(blank=True, max_length=256)),
                ('risk_level', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info'), ('Secure', 'Secure'), ('None', 'None')], default=sastf.SASTF.utils.enum.Severity['NONE'], max_length=256)),
                ('is_active', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SASTF.file')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SASTF.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('scan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SASTF.scan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('lines', models.CharField(blank=True, max_length=2048)),
                ('sys_path', models.CharField(blank=True, max_length=1024)),
                ('language', models.CharField(blank=True, max_length=32)),
                ('file_name', models.CharField(blank=True, max_length=512)),
                ('file_size', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TLS',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('tls_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=256, null=True)),
                ('recommended', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('finding_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info'), ('Secure', 'Secure'), ('None', 'None')], default=sastf.SASTF.utils.enum.Severity['NONE'], max_length=256)),
                ('discovery_date', models.DateField(auto_now_add=True, null=True)),
                ('state', models.CharField(choices=[('To Verify', 'To Verify'), ('Confirmed', 'Confirmed'), ('Urgent', 'Urgent'), ('Not Exploitable', 'Not Exploitable'), ('Proposed not exploitable', 'Proposed not exploitable')], default=sastf.SASTF.utils.enum.State['TO_VERIFY'], max_length=256)),
                ('status', models.CharField(blank=True, max_length=256)),
                ('scan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SASTF.scan')),
                ('scanner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SASTF.scanner')),
                ('snippet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SASTF.snippet')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SASTF.findingtemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('visibility', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Internal', 'Internal')], default=sastf.SASTF.utils.enum.Visibility['PRIVATE'], max_length=256)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('store_name', models.CharField(blank=True, max_length=32)),
                ('app_id', models.CharField(blank=True, max_length=512)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('score', models.FloatField(default=0.0)),
                ('installs', models.CharField(blank=True, default='0', max_length=128)),
                ('price', models.CharField(blank=True, max_length=256)),
                ('url', models.URLField(blank=True)),
                ('release_date', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SASTF.developerinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('task_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('celery_id', models.CharField(blank=True, max_length=256, null=True)),
                ('active', models.BooleanField(default=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SASTF.scan')),
                ('scanner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SASTF.scanner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SASTF.team'),
        ),
        migrations.CreateModel(
            name='PermissionFinding',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('finding_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info'), ('Secure', 'Secure'), ('None', 'None')], default=sastf.SASTF.utils.enum.Severity['NONE'], max_length=256)),
                ('discovery_date', models.DateField(auto_now_add=True, null=True)),
                ('permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SASTF.apppermission')),
                ('scan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SASTF.scan')),
                ('scanner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SASTF.scanner')),
                ('snippet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SASTF.snippet')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SASTF.findingtemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageVulnerability',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('identifier', models.UUIDField(primary_key=True, serialize=False)),
                ('cve_id', models.CharField(blank=True, max_length=256)),
                ('version', models.CharField(blank=True, max_length=512)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info'), ('Secure', 'Secure'), ('None', 'None')], default=sastf.SASTF.utils.enum.Severity['NONE'], max_length=32)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SASTF.package')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(fields=('group_id', 'artifact_id'), name='unique_package_groupid_artifactid'),
        ),
        migrations.AddField(
            model_name='host',
            name='collected_data',
            field=models.ManyToManyField(related_name='hosts', to='SASTF.datacollectiongroup'),
        ),
        migrations.AddField(
            model_name='host',
            name='scan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SASTF.scan'),
        ),
        migrations.AddField(
            model_name='host',
            name='scanner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SASTF.scanner'),
        ),
        migrations.AddField(
            model_name='host',
            name='snippet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SASTF.snippet'),
        ),
        migrations.AddField(
            model_name='host',
            name='suites',
            field=models.ManyToManyField(related_name='hosts', to='SASTF.ciphersuite'),
        ),
        migrations.AddField(
            model_name='host',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SASTF.hosttemplate'),
        ),
        migrations.AddField(
            model_name='host',
            name='tlsversions',
            field=models.ManyToManyField(related_name='hosts', to='SASTF.tls'),
        ),
        migrations.AddField(
            model_name='finding',
            name='scan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SASTF.scan'),
        ),
        migrations.AddField(
            model_name='finding',
            name='scanner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SASTF.scanner'),
        ),
        migrations.AddField(
            model_name='finding',
            name='snippet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SASTF.snippet'),
        ),
        migrations.AddField(
            model_name='finding',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SASTF.findingtemplate'),
        ),
        migrations.AddField(
            model_name='details',
            name='certificates',
            field=models.ManyToManyField(related_name='details', to='SASTF.certificate'),
        ),
        migrations.AddField(
            model_name='details',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SASTF.file'),
        ),
        migrations.AddField(
            model_name='details',
            name='scan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SASTF.scan'),
        ),
        migrations.AddField(
            model_name='details',
            name='store_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SASTF.storeinfo'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SASTF.package'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SASTF.project'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='scanner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SASTF.scanner'),
        ),
        migrations.AddField(
            model_name='component',
            name='intent_filters',
            field=models.ManyToManyField(related_name='components', to='SASTF.intentfilter'),
        ),
        migrations.AddField(
            model_name='component',
            name='permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SASTF.apppermission'),
        ),
        migrations.AddField(
            model_name='component',
            name='scanner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SASTF.scanner'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bundle',
            name='projects',
            field=models.ManyToManyField(related_name='bundles', to='SASTF.project'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
