#!/bin/bash

# same configuration as applied in compose/django/local/entrypoint
set -o errexit
set -o nounset

# Remove old process information
rm -f './celerybeat.pid'
celery -A sastf.SASTF beat -l "${CELERY_DEBUG_LEVEL}"
